chore: fix format issues in `apps/console/src/pages/_app.tsx`  (#839)
Because

Prettier checks failed in CI
```
Checking formatting...
[warn] apps/console/src/pages/_app.tsx
[warn] Code style issues found in the above file. Run Prettier to fix.
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.
```

This commit

- Fixes the formatting issues in `apps/console/src/pages/_app.tsx`

Signed-off-by: Hung-Han (Henry) Chen <chenhungh@gmail.com>